### ISSUE TITLE
ColoradoHydroBaseRest DivTotal test needs units

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/cdss-app-tstool-test#6]
I ran the TSTool test Test_TSID_ColoradoHydroBaseRest_ColoradoHydroBaseRest_CompareHydroBase_DivTotal_Month.TSTool.  The REST API time series does not have units set.  A symptom of this is that if the time series are viewed in a table different number of digits are used for each time series.  If the units are the same, the number of digits will be the same (see ***View / Data Units*** precision in TSTool).   TS.setDataUnits and TS.setDataUnitsOriginal should be set for all time series to set data units.  Data units are very important.  The diversion records have  data like:

```
<DivRecDay xmlns="">
<approvalStatus>Approved</approvalStatus>
<dataMeasDate>1970-05-30T00:00:00</dataMeasDate>
<dataValue>92.00</dataValue>
<measInterval>Daily</measInterval>
<measUnits>CFS</measUnits>
<modified>2001-08-14T18:04:00</modified>
<obsCode>* </obsCode>
<waterClassNum>54271</waterClassNum>
<wcIdentifier>0100501 S:1 F: U:0 T: G: To:</wcIdentifier>
<wdid>0100501</wdid>
</DivRecDay>
```

The `measUnits` clearly provide units.  One option would be that when reading the time series keep track if units have been set with a boolean so it is only set after the first record is processed.  The units could also be set for every record but that would be a slight performance hit.   The units do not seem to be available in water classes so they can only be set by the detailed records.

I did not check the other time series, but all time series need to have units set if at all possible, without hard-coding the units.

**Comment by jurentie** [comment]
Updated ColoradoHydroBaseRestDataStore.java. Previously data units were being set for daily data but was not added to monthly and yearly data, this has been fixed.
[Commit made in cdss-lib-dmi-hydrobase-rest-java](https://github.com/OpenWaterFoundation/cdss-lib-dmi-hydrobase-rest-java/commit/cc5db79093b713f78a7f5678318d27a539ce56ee)
